### ISSUE TITLE
Use separate files for js, css and html?

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/BlastNAttack#1]
Is this example so large that it warrants separation js, css, and html? Is your preference still one mammoth file?

**Comment by HGustavs** [comment]
It is still not even Mammuthus exilis sized, so to call it a mammoth is a very big stretch of the word.

**Comment by HGustavs** [comment]
If it gets bigger later on, and does not fit well with the code viewer when it is finished, lets change it up, but for now lets keep it in an easy readable state.

**Comment by a97marbr** [comment]
:) sure ... no problem.
